let pokeCards = [
    {
        name:"Bulbasaur",
        typ:{
            typ01:"grass",
            typ02:"poison"
        },
        main_attr:{
            height:0.6,
            weight:8.5,
            baseExp:62,
        },
        stats_attr:{
            hp:45,
            max_hp:294,
            attack:49,
            max_attack:216,
            defence:49,
            max_defence:216,
            specialAttack:65,
            max_sp_attack:251,
            speed:45,
            max_speed:207
        },
        evo_chain_attr:{
            first:"bulbasaur",
            second:"ivysaur",
            third:"venusaur"
        }
    },
        {
        name:"Charmander",
        typ:{
            typ01:"fire",
            typ02:"none"
        },
        main_attr:{
            height:0.6,
            weight:8.7,
            baseExp:63,
        },
        stats_attr:{
            hp:39,
            attack:52,
            defence:43,
            specialAttack:60,
            speed:65,
            max_hp:282,
            max_attack:223,
            max_defence:203,
            max_sp_attack:240,
            max_speed:251,
        },
        evo_chain_attr:{
            first:"charmander",
            second:"charmeleon",
            third:"charizard"
        }
    },
        {
        name:"Squirtle",
        typ:{
            typ01:"water",
            typ02:"none"
        },
        main_attr:{
            height:0.5,
            weight:9,
            baseExp:63,
        },
        stats_attr:{
            hp:44,
            attack:48,
            defence:65,
            specialAttack:50,
            speed:43,
            max_hp:292,
            max_attack:214,
            max_defence:251,
            max_sp_attack:218,
            max_speed:203
        },
        evo_chain_attr:{
            first:"squirtle",
            second:"wartortle",
            third:"blastoise"
        }
    }

]